# Podcasters CRUD

# GET ALL PODCASTERS
GET http://localhost:5173/api/podcasters HTTP/1.1

# CREATE NEW PODCASTER
###
POST http://localhost:5173/api/podcasters HTTP/1.1
content-type: application/json

{
    "username" : "somenew@podcaster.com",
    "password" : "Examplepass@02",
    "name" : "Example Podcaster"
}


# LOGIN AS PODCASTER
###
POST http://localhost:5173/api/podcasterlogin HTTP/1.1
content-type: application/json

{
    "username" : "somenew@podcaster.com",
    "password" : "Examplepass@02"
}

# ADD PODCAST AS A PODCASTER
###
POST http://localhost:5173/api/podcasters/36/podcasts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbWVuZXdAcG9kY2FzdGVyLmNvbSIsImlkIjo1MiwiaWF0IjoxNzMxMjY1NDUzLCJleHAiOjE3MzEyNjkwNTN9.0ggcGX2d8Bs7aDrb18GMVSNPW055BvJRB5sBi6HTEmE

{
    "name" : "This is a podcast name",
    "description": "This is a very thourough descrption of this added podcast where I am trying to create a placeholder",
    "urls": ["thisisaurl.com"]
}

# VERIFY AND DISABLE PODCASTER BY SUPEUSER AND ADMIN
###
PATCH http://localhost:5173/api/podcasters/41 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVyQHVzZXIuY29tIiwiaWQiOjE1LCJyb2xlIjoic3VwZXJ1c2VyIiwiaWF0IjoxNzMxMjY0NDE5LCJleHAiOjE3MzEyNjgwMTl9.081deB_K2AQsqZ2bZybMRQINNxnHm9xeTE05atXJmCA

{   
    "verified": true,
    "disabled": true
}
# UPDATE INFO OF PODCASTER BY LOGGEDIN PODCASTER
###
PUT http://localhost:5173/api/podcasters/52 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbWVuZXdAcG9kY2FzdGVyLmNvbSIsImlkIjo1MiwiaWF0IjoxNzMxMjY1NTUzLCJleHAiOjE3MzEyNjkxNTN9.OoWcVllYudIinXGbaZ67ZHB4NgL6_ADN7qxHyMJE480

{   
    "name" : "upddatedname",
    "links" : ["this is an updated link"],
    "about": "thisi is an updated bio",
    "avatar_url": "thisisuorl.com"
}



# DELETE PODCASTER 
###
DELETE http://localhost:5173/api/podcasters/49 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV4YW1wbGVAcG9kY2FzdGVyLmNvbSIsImlkIjo0OSwiaWF0IjoxNzMxMDE1NTg1LCJleHAiOjE3MzEwMTkxODV9.1h2-wFyBeprhvuWxaeDjXIB_f6O3BGEHpNnWKqhc-5I