# Podcasters CRUD

# GET ALL PODCASTERS
GET http://localhost:5173/api/podcasters HTTP/1.1

# CREATE NEW PODCASTER
###
POST http://localhost:5173/api/podcasters HTTP/1.1
content-type: application/json

{
    "username" : "somenew@podcaster.com",
    "password" : "Examplepass@02",
    "name" : "Example Podcaster"
}


# LOGIN AS PODCASTER
###
POST http://localhost:5173/api/podcasterlogin HTTP/1.1
content-type: application/json

{
    "username" : "example@podcaster.com",
    "password" : "Examplepass@02"
}

# ADD PODCAST AS A PODCASTER
###
POST http://localhost:5173/api/podcasters/49/podcasts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV4YW1wbGVAcG9kY2FzdGVyLmNvbSIsImlkIjo0OSwiaWF0IjoxNzMxMDE1NTg1LCJleHAiOjE3MzEwMTkxODV9.1h2-wFyBeprhvuWxaeDjXIB_f6O3BGEHpNnWKqhc-5I

{
    "name" : "This is a podcast name",
    "description": "This is a very thourough descrption of this added podcast where I am trying to create a placeholder",
    "urls": ["thisisaurl.com"]
}

# BULK EDIT OF PODCASTER DATA BY PODCASTER
###
PUT http://localhost:5173/api/podcasters/41 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlckB1c2VyLmNvbSIsImlkIjoxNCwicm9sZSI6InN1cGVydXNlciIsImlhdCI6MTczMTIyNzY1OCwiZXhwIjoxNzMxMjMxMjU4fQ.hcXSazOOUF4dgBPK9EnpsP7KbamGI1QXjLBpmCJkB20

{
    
    "verified": true,
    "disabled": true
}

# DELETE PODCASTER 
###
DELETE http://localhost:5173/api/podcasters/49 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV4YW1wbGVAcG9kY2FzdGVyLmNvbSIsImlkIjo0OSwiaWF0IjoxNzMxMDE1NTg1LCJleHAiOjE3MzEwMTkxODV9.1h2-wFyBeprhvuWxaeDjXIB_f6O3BGEHpNnWKqhc-5I