# USERS CRUD
# GET ALL USERS WITH FOLLOWINGS AND SUBS
GET http://localhost:5173/api/users HTTP/1.1

###
# CREATE NEW USER
POST http://localhost:5173/api/users HTTP/1.1
content-type: application/json

{
    "username" : "somenew@user.com",
    "password" : "Examplepass@02",
    "name" : "Example user"
}

###
# USER LOGIN
POST http://localhost:5173/api/userlogin HTTP/1.1
content-type: application/json

{
    "username" : "somenew@user.com",
    "password" : "Examplepass@02"
}

###
# GET SINGLE USER
GET http://localhost:5173/api/users/3 HTTP/1.1

###
#

